/**
 * Next Level — media build step
 * ------------------------------------------------------------
 * Scans /students for videos and generates lightweight web assets:
 *   • A poster frame (JPG) for every video, so pages never have to
 *     download a 20–200 MB file just to show a thumbnail.
 *   • Video durations (shown on the catalog cards).
 *   • A short, muted, compressed hero montage for the home page.
 *   • A web-sized copy of large portrait images.
 *
 * Output: /assets/media/**  and  /assets/js/media-manifest.js
 * Run:    npm run media
 */
import { spawnSync } from "node:child_process";
import { readdirSync, statSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, extname, basename, posix, sep } from "node:path";
import ffmpegPath from "ffmpeg-static";

const ROOT = process.cwd();
const STUDENTS = join(ROOT, "students");
const OUT = join(ROOT, "assets", "media");
const POSTERS = join(OUT, "posters");
mkdirSync(POSTERS, { recursive: true });

const toWeb = (abs) => relative(ROOT, abs).split(sep).join(posix.sep);
const slug = (s) => s.toLowerCase().replace(/\.[a-z0-9]+$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

function ff(args) {
  const r = spawnSync(ffmpegPath, ["-hide_banner", "-y", ...args], { encoding: "utf8", maxBuffer: 1 << 26 });
  return r;
}

function probeDuration(file) {
  const r = spawnSync(ffmpegPath, ["-hide_banner", "-i", file], { encoding: "utf8" });
  const m = /Duration: (\d+):(\d+):(\d+\.\d+)/.exec(r.stderr || "");
  return m ? Math.round(+m[1] * 3600 + +m[2] * 60 + +m[3]) : null;
}

const videos = walk(STUDENTS).filter((f) => extname(f).toLowerCase() === ".mp4");
const manifest = {};

for (const file of videos) {
  const web = toWeb(file);
  const duration = probeDuration(file);
  // Use a frame ~25% into short clips (avoids black lead-in frames), capped at 4s.
  const at = duration ? Math.min(4, Math.max(0.5, duration * 0.25)) : 1;
  const posterName = slug(web.replace(/^students\//, "")) + ".jpg";
  const posterAbs = join(POSTERS, posterName);
  if (!existsSync(posterAbs)) {
    ff(["-ss", String(at), "-i", file, "-frames:v", "1", "-vf", "scale='min(1280,iw)':-2", "-q:v", "4", posterAbs]);
  }
  manifest[web] = { poster: toWeb(posterAbs), duration };
  console.log(`✓ ${web}  (${duration ?? "?"}s)`);
}

// ---- Hero montage: 4 short clips → 1 silent, compressed loop ----
const heroClips = [
  ["students/Kegan B/Videos/Kegan-Fh-demo.mp4", 3],
  ["students/Madison S/Drills/Under The Rope Going Forward/under-the-rope-going-forward.mp4", 6],
  ["students/Kegan B/Videos/Kegan-Side-serve-Demo.mp4", 3],
  ["students/Madison S/Videos/side-Forhand.mp4", 4],
].filter(([p]) => existsSync(join(ROOT, p)));

const heroOut = join(OUT, "hero-loop.mp4");
if (heroClips.length && !existsSync(heroOut)) {
  const SEG = 3;
  const inputs = heroClips.flatMap(([p, ss]) => ["-ss", String(ss), "-t", String(SEG), "-i", join(ROOT, p)]);
  const chains = heroClips
    .map((_, i) => `[${i}:v]scale=1600:900:force_original_aspect_ratio=increase,crop=1600:900,fps=30,setsar=1,format=yuv420p[v${i}]`)
    .join(";");
  const concat = heroClips.map((_, i) => `[v${i}]`).join("") + `concat=n=${heroClips.length}:v=1:a=0[out]`;
  const r = ff([
    ...inputs,
    "-filter_complex", `${chains};${concat}`,
    "-map", "[out]", "-an",
    "-c:v", "libx264", "-preset", "slow", "-crf", "28", "-movflags", "+faststart",
    heroOut,
  ]);
  if (r.status !== 0) console.error(r.stderr.slice(-1500));
  ff(["-ss", "0.2", "-i", heroOut, "-frames:v", "1", "-q:v", "4", join(OUT, "hero-poster.jpg")]);
  console.log("✓ hero-loop.mp4");
}

// ---- Web-sized images for oversized originals ----
const bigImages = [
  ["students/Madison S/Profile/madison-profile.png", "madison-portrait.jpg", 1000],
];
for (const [src, name, w] of bigImages) {
  const out = join(OUT, name);
  if (existsSync(join(ROOT, src)) && !existsSync(out)) {
    ff(["-i", join(ROOT, src), "-vf", `scale=${w}:-2`, "-q:v", "4", out]);
    console.log(`✓ ${name}`);
  }
}

writeFileSync(
  join(ROOT, "assets", "js", "media-manifest.js"),
  "/* AUTO-GENERATED by tools/build-media.mjs — do not edit by hand. */\nwindow.NL_MEDIA = " +
    JSON.stringify(manifest, null, 2) +
    ";\n"
);
console.log(`\nDone. ${videos.length} videos processed.`);
